Repository woowa-techcamp-2021/store-4, pull requests merged in 2021-08, with the labels that each got.

#1 풀리퀘스트 템플릿 체크리스트 추가
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#11 리뷰어 자동 할당 스크립트
  .github/reviewer-lottery.yml
Labels: feature

#12 reviewer-lottery 워크플로우 추가
  .github/workflows/reviewer-lottery.yml
Labels: feature

#13 프로젝트 기본 세팅
  client/.babelrc
  client/.eslintrc.js
  client/.gitignore
  client/.prettierrc.js
  client/jest.config.js
  client/package-lock.json
  client/package.json
  client/src/components/App.test.tsx
  client/src/components/App.tsx
  client/src/index.html
  client/src/index.tsx
  client/tsconfig.json
  client/webpack.common.js
  client/webpack.dev.js
  client/webpack.prod.js
  server/.eslintrc.js
  server/.gitignore
  server/.prettierrc.js
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/tsconfig.json
Labels: feature, frontend, backend

#14 [#5] 폴더 구조 정의, Database 연결, loader 설정
  .gitignore
  server/package-lock.json
  server/package.json
  server/src/.env.sample
  server/src/app.ts
  server/src/config/dotenv.ts
  server/src/controllers/.gitkeep
  server/src/database.ts
  server/src/loaders/db-loader.ts
  server/src/loaders/express-loader.ts
  server/src/loaders/index.ts
  server/src/middlewares/.gitkeep
  server/src/models/.gitkeep
  server/src/models/User.ts
  server/src/repositories/.gitkeep
  server/src/routers/.gitkeep
  server/src/services/.gitkeep
  server/src/util/type-guard.ts
Labels: feature, backend

#17 [#3] 프론트엔드 폴더 구조 정의
  client/src/api/.gitkeep
  client/src/components/.gitkeep
  client/src/components/App.test.tsx
  client/src/components/App.tsx
  client/src/containers/.gitkeep
  client/src/hooks/.gitkeep
  client/src/lib/.gitkeep
  client/src/pages/Home.tsx
  client/src/styles/.gitkeep
  client/src/utils/.gitkeep
Labels: feature, frontend

#19 [#16] 백엔드 테이블 모델링
  server/package-lock.json
  server/src/loaders/db-loader.ts
  server/src/models/.gitkeep
  server/src/models/User.ts
  server/src/models/Wish.ts
  server/src/models/category.ts
  server/src/models/delivery-address.ts
  server/src/models/index.ts
  server/src/models/order-detail.ts
  server/src/models/order.ts
  server/src/models/product-image.ts
  server/src/models/product-option.ts
  server/src/models/product-select.ts
  server/src/models/product.ts
  server/src/models/review-image.ts
  server/src/models/review.ts
  server/src/models/timestamp.ts
  server/src/models/user.ts
Labels: feature, backend

#23 [#22] 프로젝트 ESLint, Jest Actions로 확인
  .github/reviewer-lottery.yml
  .github/workflows/jest.yml
  .github/workflows/lint.yml
  client/package.json
  client/src/jest.test.ts
  server/package.json
Labels: feature, backend

#25 [#6] Oauth 백엔드 로직 (Google, Facebook)
  server/.env.sample
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/config/dotenv.ts
  server/src/controllers/.gitkeep
  server/src/controllers/auth.controller.ts
  server/src/loaders/express-loader.ts
  server/src/repositories/user-repository.ts
  server/src/routers/.gitkeep
  server/src/routers/api/index.ts
  server/src/routers/auth/index.ts
  server/src/services/.gitkeep
  server/src/services/jwt.service.ts
  server/src/services/user.service.ts
  server/src/third-party-auth/facebook.ts
  server/src/third-party-auth/google.ts
  server/src/util/build-query-string.ts
Labels: feature, backend

#26 [#4] React router 컴포넌트 구현
  client/src/lib/.gitkeep
  client/src/lib/router.tsx
  client/src/utils/.gitkeep
  client/src/utils/typeGuard.ts
  client/webpack.dev.js
Labels: feature, frontend

#24 [#10] 상품목록 UI 작업
  client/index.d.ts
  client/package-lock.json
  client/package.json
  client/src/assets/images/towel.png
  client/src/components/.gitkeep
  client/src/components/ProductList/ProductItem.tsx
  client/src/components/ProductList/ProductList.tsx
  client/src/components/ProductList/mock/api.ts
  client/src/components/ProductList/mock/data.ts
  client/src/index.tsx
  client/src/types/product.ts
  client/src/utils/moneyFormater.ts
  client/src/utils/range.ts
  client/tsconfig.json
Labels: feature, frontend

#32 [#30] 카테고리 조회 API
  server/package-lock.json
  server/package.json
  server/src/controllers/category-controller.ts
  server/src/models/category.ts
  server/src/repositories/category-repository.ts
  server/src/routers/api/category/index.ts
  server/src/routers/api/index.ts
  server/src/services/category-service.ts
Labels: feature, backend

#36 [#18] 서버 배포
  .github/workflows/dev-server-cd.yml
  server/package.json
Labels: feature, backend

#33 [#7] OAuth 회원가입, 로그인 UI 및 동작
  client/.env.sample
  client/jest.config.js
  client/package-lock.json
  client/package.json
  client/src/components/login/Login.test.tsx
  client/src/components/login/Login.tsx
  client/src/components/login/OAuthButton.tsx
  client/src/components/login/facebook.svg
  client/src/components/login/google.svg
  client/src/components/login/kakao.svg
  client/webpack.dev.js
Labels: feature, frontend

#45 [#15] 에러 미들웨어 등록
  server/src/app.ts
  server/src/exceptions/business-exception.ts
  server/src/lib/wrap-async.ts
  server/src/middlewares/error-middleware.ts
Labels: feature, backend

#46 [#31] 인증 미들웨어 작성
  server/src/app.ts
  server/src/exceptions/invaild-token-exception.ts
  server/src/exceptions/token-expired-exception.ts
  server/src/middlewares/auth-middleware.ts
  server/src/middlewares/error-middleware.ts
  server/src/routers/api/category/index.ts
  server/src/services/jwt.service.ts
  server/src/types/express.d.ts
  server/src/util/type-guard.ts
  server/tsconfig.json
Labels: feature, backend

#47 [#29] 헤더 UI 및 최소 기능
  client/src/components/Header/Header.tsx
  client/src/components/Header/HeaderMain/CategoryMenu/CategoryLayer.tsx
  client/src/components/Header/HeaderMain/CategoryMenu/CategoryMenu.tsx
  client/src/components/Header/HeaderMain/CategoryMenu/dummy.ts
  client/src/components/Header/HeaderMain/CategoryMenu/menuIcon.png
  client/src/components/Header/HeaderMain/HeaderMain.tsx
  client/src/components/Header/HeaderMain/SearchBar/SearchBar.tsx
  client/src/components/Header/HeaderMain/SearchBar/searchIcon.svg
  client/src/components/Header/HeaderMain/logo.png
  client/src/components/Header/NavBar/NavBar.tsx
  client/src/index.html
  client/src/index.tsx
Labels: feature, frontend

#48 [#28] - 메인페이지 UI 작업(캐러셀 제외)
  client/src/components/MainProductSections/MainAdList/MainAdList.tsx
  client/src/components/MainProductSections/MainAdList/MainAdListItem.tsx
  client/src/components/MainProductSections/MainProductList.tsx
  client/src/components/MainProductSections/MainProductSections.tsx
  client/src/components/MainProductSections/hooks/useProductAdList.ts
  client/src/components/MainProductSections/hooks/useProductList.ts
  client/src/components/MainProductSections/mock/hyoja_pc.png
  client/src/components/MainProductSections/mock/index.ts
  client/src/components/MainProductSections/mock/pc_kkfakeset.png
  client/src/components/ProductList/ProductItem.tsx
  client/src/components/ProductList/ProductList.tsx
Labels: feature, frontend

#34 [#8] 상품 목록 API
  server/src/controllers/auth-controller.ts
  server/src/controllers/product-controller.ts
  server/src/dummy-data/category.ts
  server/src/dummy-data/order-detail.ts
  server/src/dummy-data/order.ts
  server/src/dummy-data/product.ts
  server/src/dummy-data/reviews.ts
  server/src/loaders/db-loader.ts
  server/src/models/category.ts
  server/src/models/order-detail.ts
  server/src/models/order.ts
  server/src/models/product.ts
  server/src/repositories/order-detail-repository.ts
  server/src/repositories/product-repository.ts
  server/src/repositories/review-repository.ts
  server/src/routers/api/index.ts
  server/src/routers/api/product/index.ts
  server/src/routers/auth/index.ts
  server/src/services/jwt-service.ts
  server/src/services/order-detail-service.ts
  server/src/services/product-service.ts
  server/src/services/review-service.ts
  server/src/services/user-service.ts
Labels: feature, backend

#50 fix: auth-middleware import 에러
  server/src/middlewares/auth-middleware.ts
Labels: bug, backend

#51 [#38] 프론트엔드 테스트 (OauthButton)
  client/package.json
  client/src/components/login/OAuthButton.test.tsx
Labels: feature, frontend

#52 [#39] 프론트엔드 공통 스타일링
  client/module.d.ts
  client/package-lock.json
  client/package.json
  client/src/components/App/App.tsx
  client/src/components/login/Login.test.tsx
  client/src/components/login/Login.tsx
  client/src/index.html
  client/src/index.tsx
  client/src/lib/provideTheme2Test.tsx
  client/src/styles/.gitkeep
  client/src/styles/global.ts
  client/src/styles/styles.d.ts
  client/src/styles/theme.ts
  client/tsconfig.json
Labels: feature, frontend

#53 [#40] MobX 기본 구조 설계 및 카테고리 Store 개발
  client/.babelrc
  client/package-lock.json
  client/package.json
  client/src/api/.gitkeep
  client/src/models/category.ts
  client/src/stores/categoryStore.ts
  client/tsconfig.json
Labels: feature, frontend

#54 [#41] 프론트엔드 네트워크 라이브러리 개발
  client/src/api/category.ts
  client/src/api/index.ts
  client/src/lib/request.ts
  client/src/models/category.ts
  client/src/stores/categoryStore.ts
  client/src/types/category.ts
  client/src/utils/build-query-string.ts
Labels: feature, frontend

#57 [#42] 프론트엔드 컴포넌트 역할 정의, 분리(로그인 컴포넌트)
  client/src/assets/icons/facebook.svg
  client/src/assets/icons/google.svg
  client/src/assets/icons/kakao.svg
  client/src/components/App/App.tsx
  client/src/components/MainProductSections/MainProductSections.tsx
  client/src/components/login/Login.test.tsx
  client/src/components/login/Login.tsx
  client/src/containers/LoginContainer.tsx
  client/src/pages/Home.tsx
  client/src/pages/Login.tsx
Labels: feature, frontend

#58 [#43] 에러 미들웨어 사용 예 작성 (상품목록 API: PageOverflow)
  server/src/exceptions/page-overflow-exception.ts
  server/src/middlewares/.gitkeep
  server/src/middlewares/error-middleware.ts
  server/src/routers/api/product/index.ts
  server/src/services/product-service.ts
Labels: feature, backend

#71 [#70] 데이터 삽입 SQL
  server/init.sql
  server/src/loaders/db-loader.ts
Labels: feature, backend

#73 [#72] 로그인 페이지 컴포넌트 컨벤션 수정
  client/src/components/Login/Login.test.tsx
  client/src/components/Login/Login.tsx
  client/src/components/Login/OAuthButton.test.tsx
  client/src/components/Login/OAuthButton.tsx
  client/src/containers/LoginContainer.tsx
Labels: feature, frontend

#74 [#49] 타입스크립트 컴파일 오류 확인 CI
  .github/workflows/typescript-compile.yml
Labels: feature, frontend, backend

#76 [#69] 전역 상태: optionStore 작성
  client/src/components/ProductList/mock/api.ts
  client/src/stores/optionStore.ts
  client/src/types/option.ts
  client/src/types/product.ts
Labels: feature, frontend

#75 [#29] 헤더 UI / 최소 기능 (컨벤션에 맞게 리팩토링)
  client/src/components/Header/Header.tsx
  client/src/components/Header/HeaderMain/CategoryMenu/CategoryLayer.test.tsx
  client/src/components/Header/HeaderMain/CategoryMenu/CategoryLayer.tsx
  client/src/components/Header/HeaderMain/CategoryMenu/CategoryMenu.tsx
  client/src/components/Header/HeaderMain/CategoryMenu/dummy.ts
  client/src/components/Header/HeaderMain/HeaderMain.tsx
  client/src/components/Header/NavBar/NavBar.tsx
  client/src/containers/.gitkeep
  client/src/containers/CategoryLayerContainer.tsx
  client/src/stores/categoryStore.ts
  client/src/styles/global.ts
Labels: feature, frontend

#82 [#81] 더미데이터 및 관련 코드 제거
  server/src/dummy-data/category.ts
  server/src/dummy-data/order-detail.ts
  server/src/dummy-data/order.ts
  server/src/dummy-data/product.ts
  server/src/dummy-data/reviews.ts
  server/src/repositories/product-repository.ts
Labels: backend

#83 [#78] Product 모델 id 타입 수정
  server/src/models/product.ts
  server/src/repositories/order-detail-repository.ts
  server/src/repositories/review-repository.ts
  server/src/services/order-detail-service.ts
  server/src/services/review-service.ts
Labels: backend

#84 [#62] 상품 개별 조회 API
  server/src/controllers/auth-controller.ts
  server/src/controllers/product-controller.ts
  server/src/exceptions/product-notfound-exception.ts
  server/src/repositories/product-repository.ts
  server/src/repositories/wish-repository.ts
  server/src/routers/api/product/index.ts
  server/src/services/jwt-service.ts
  server/src/services/product-service.ts
  server/src/services/user-service.ts
  server/src/types/express.d.ts
Labels: feature, backend

#80 [#61] 상품 상세 페이지 이미지 보기 기능
  client/src/components/ProductDetail/MagnifierImage.test.tsx
  client/src/components/ProductDetail/MagnifierImage.tsx
  client/src/components/ProductDetail/ProductDetailImage.test.tsx
  client/src/components/ProductDetail/ProductDetailImages.tsx
Labels: feature, frontend

#77 메인 페이지에 들어갈 캐러셀 구현
  client/jest.config.js
  client/module.d.ts
  client/src/components/Carousel/Carousel.test.tsx
  client/src/components/Carousel/Carousel.tsx
  client/src/components/Carousel/CarouselController.test.tsx
  client/src/components/Carousel/CarouselController.tsx
  client/src/components/Carousel/CarouselItem.tsx
  client/src/components/Carousel/hooks/useInfiniteSlide.ts
  client/src/components/Carousel/mock/beer.gif
  client/src/components/Carousel/mock/bottle.gif
  client/src/components/Carousel/mock/pencil.gif
  client/src/containers/CarouselContainer.tsx
  client/src/pages/Home.tsx
  client/src/styles/animation.ts
  client/webpack.common.js
Labels: feature, frontend

#87 [#85] 상품 관련 프론트엔드 모델 정의
  client/src/models/product-image.ts
  client/src/models/product-option.ts
  client/src/models/product-select.ts
  client/src/models/product.test.tsx
  client/src/models/product.ts
  client/src/models/review-image.ts
  client/src/models/review.ts
Labels: feature, frontend

#89 [#86] 상품목록 API 리팩토링
  server/package-lock.json
  server/package.json
  server/src/controllers/product-controller.ts
  server/src/repositories/order-detail-repository.ts
  server/src/repositories/product-repository.ts
  server/src/repositories/review-repository.ts
  server/src/services/order-detail-service.ts
  server/src/services/product-service.ts
  server/src/services/review-service.ts
Labels: refactor, backend

#93 [#63] 찜하기 API
  server/src/controllers/wish-controller.ts
  server/src/exceptions/invalid-path-parameter-exception.ts
  server/src/exceptions/unauthenticated-exception.ts
  server/src/exceptions/user-notfound-exception.ts
  server/src/middlewares/error-middleware.ts
  server/src/models/wish.ts
  server/src/routers/api/product/index.ts
  server/src/services/user-service.ts
  server/src/services/wish-service.ts
Labels: feature, backend

#94 [#59] 프론트엔드 production 시에 env 설정
  .github/workflows/dev-server-cd.yml
  client/webpack.prod.js
Labels: bug, frontend

#100 [#99] 백엔드 검증 모듈 추가 및 레거시 제거
  server/package-lock.json
  server/package.json
  server/src/controllers/product-controller.ts
  server/src/enum/product.ts
  server/src/exceptions/invalid-input-exception.ts
  server/src/exceptions/invalid-token-exception.ts
  server/src/middlewares/auth-middleware.ts
  server/src/middlewares/error-middleware.ts
  server/src/repositories/product-repository.ts
  server/src/services/product-service.ts
  server/src/validations/base-validator.ts
  server/src/validations/number-params.ts
  server/src/validations/product-find-query.ts
Labels: enhancement, feature, backend

#91 [#67] 상품목록 페이지 UI , API 연동
  client/src/api/index.ts
  client/src/api/product.ts
  client/src/assets/images/no-image.png
  client/src/components/App/App.tsx
  client/src/components/Header/HeaderMain/CategoryMenu/CategoryLayer.test.tsx
  client/src/components/Header/HeaderMain/CategoryMenu/CategoryLayer.tsx
  client/src/components/MainProductSections/MainProductList.tsx
  client/src/components/MainProductSections/MainProductSections.tsx
  client/src/components/MainProductSections/hooks/useProductList.ts
  client/src/components/MainProductSections/mock/index.ts
  client/src/components/ProductList/ProductItem.test.tsx
  client/src/components/ProductList/ProductItem.tsx
  client/src/components/ProductList/ProductItem/ProductItem.tsx
  client/src/components/ProductList/ProductItem/ProductItemDescription.tsx
  client/src/components/ProductList/ProductItem/ProductItemImage.tsx
  client/src/components/ProductList/ProductList.test.tsx
  client/src/components/ProductList/ProductList.tsx
  client/src/components/ProductList/ProductListHeader.tsx
  client/src/components/ProductList/SortButtonList.test.tsx
  client/src/components/ProductList/SortButtonList.tsx
  client/src/containers/CategoryLayerContainer.tsx
  client/src/containers/ProductListContainer.tsx
  client/src/jest.test.ts
  client/src/lib/provideRouter2Test.tsx
  client/src/models/product.ts
  client/src/pages/Products.tsx
  client/src/stores/optionStore.ts
  client/src/stores/productStore.ts
  client/src/types/option.ts
  client/src/types/product.ts
  client/src/utils/build-query-string.ts
Labels: feature, frontend

#98 [#64] 상품 리뷰 컴포넌트 (목록, 작성 UI)
  client/src/components/Review/Review.test.tsx
  client/src/components/Review/Review.tsx
  client/src/components/Review/ReviewHeader/ReviewHeader.tsx
  client/src/components/Review/ReviewList/ReviewList.tsx
  client/src/components/Review/ReviewList/ReviewListItem/ReviewDetail/ReviewDetail.tsx
  client/src/components/Review/ReviewList/ReviewListItem/ReviewDetail/ReviewDetailImage/ReviewDetailImage.tsx
  client/src/components/Review/ReviewList/ReviewListItem/ReviewListItem.tsx
  client/src/components/Review/ReviewList/ReviewListItem/ReviewSummary/ReviewSummary.tsx
  client/src/components/Review/ReviewList/ReviewListItem/ReviewSummary/chevronDown.png
  client/src/components/Review/ReviewList/ReviewListItem/Star/Star.tsx
  client/src/components/Review/ReviewPagination/ReviewPagination.tsx
  client/src/components/Review/ReviewPost/ReviewPost.tsx
  client/src/components/Review/ReviewPost/ReviewPostModal/ReviewPostForm/ReviewPostButtonGroup/ReviewPostButtonGroup.tsx
  client/src/components/Review/ReviewPost/ReviewPostModal/ReviewPostForm/ReviewPostForm.tsx
  client/src/components/Review/ReviewPost/ReviewPostModal/ReviewPostForm/ReviewPostImages/ReviewPostImages.tsx
  client/src/components/Review/ReviewPost/ReviewPostModal/ReviewPostForm/ReviewPostStars/ReviewPostStars.tsx
  client/src/components/Review/ReviewPost/ReviewPostModal/ReviewPostForm/ReviewPostText/ReviewPostText.tsx
  client/src/components/Review/ReviewPost/ReviewPostModal/ReviewPostModal.tsx
  client/src/containers/ReviewContainer.tsx
  client/src/containers/ReviewPostFormContainer.tsx
  client/src/utils/formatDate.ts
  client/src/utils/getPaginatedArray.ts
Labels: feature, frontend

#97 [#96] 상품 상세페이지 - 옵션 선택
  client/src/components/ProductDetail/ProductCartItem.test.tsx
  client/src/components/ProductDetail/ProductCartItem.tsx
  client/src/components/ProductDetail/ProductCounter.test.tsx
  client/src/components/ProductDetail/ProductCounter.tsx
  client/src/components/ProductDetail/ProductInfoBox.test.tsx
  client/src/components/ProductDetail/ProductInfoBox.tsx
  client/src/components/ProductDetail/ProductSelectBox.test.tsx
  client/src/components/ProductDetail/ProductSelectBox.tsx
  client/src/containers/ProductDetailContainer.tsx
  client/src/hooks/.gitkeep
  client/src/hooks/useCarstInProduct.ts
  client/src/hooks/useDetailProduct.ts
  client/src/hooks/useSelectsWithSelected.ts
  client/src/index.html
  client/src/models/cart-in-product.ts
  client/src/styles/global.ts
  client/src/styles/styles.d.ts
  client/src/styles/theme.ts
  client/src/types/product.ts
  client/src/utils/uuid.ts
Labels: feature, frontend

#104 [#103] 백엔드 서버 CD 스크립트 버그 수정
  .github/workflows/dev-server-cd.yml
Labels: bug, backend

#111 [#110] Notfound 페이지 레이아웃과 기능 구현
  client/src/pages/Notfound.tsx
Labels: feature, frontend

#106 [#60] 상품 상세페이지 UI 로직
  client/src/components/App/App.tsx
  client/src/components/ProductDetail/ProductCart/ProductCartItem.test.tsx
  client/src/components/ProductDetail/ProductCart/ProductCartItem.tsx
  client/src/components/ProductDetail/ProductCart/ProductCounter.test.tsx
  client/src/components/ProductDetail/ProductCart/ProductCounter.tsx
  client/src/components/ProductDetail/ProductDetail.tsx
  client/src/components/ProductDetail/ProductDetailSkeleton.tsx
  client/src/components/ProductDetail/ProductImage/MagnifierImage.test.tsx
  client/src/components/ProductDetail/ProductImage/MagnifierImage.tsx
  client/src/components/ProductDetail/ProductImage/ProductDetailImage.test.tsx
  client/src/components/ProductDetail/ProductImage/ProductDetailImages.tsx
  client/src/components/ProductDetail/ProductInfoBox.tsx
  client/src/containers/ProductDetailContainer.tsx
  client/src/hooks/useCartsInProduct.ts
  client/src/hooks/useDetailProduct.ts
  client/src/pages/Product.tsx
Labels: feature, frontend

#108 [#101] 배송지 관리 UI 및 로직
  client/src/components/DeliveryAddress/CreateDeliveryAddressForm.tsx
  client/src/components/DeliveryAddress/DeliveryAddressForm.tsx
  client/src/components/DeliveryAddress/DeliveryAddressItem/DeliveryAddressItem.tsx
  client/src/components/DeliveryAddress/DeliveryAddressItem/ModifyDeliveryAddresForm.tsx
  client/src/components/DeliveryAddress/DeliveryAddressList.test.tsx
  client/src/components/DeliveryAddress/DeliveryAddressList.tsx
  client/src/containers/DeliveryAddressItemContainer.tsx
  client/src/containers/ManageDeliveryAddressContainer.tsx
  client/src/models/delivery-address.ts
Labels: feature, frontend

#112 [#107] 메인 상품 조회 API
  server/src/controllers/product-controller.ts
  server/src/repositories/product-repository.ts
  server/src/routers/api/product/index.ts
  server/src/services/product-service.ts
Labels: feature, backend

#116 [#115] 컴포넌트 병합 및 UI 수정
  client/src/components/App/App.tsx
  client/src/components/Header/HeaderMain/HeaderMain.tsx
  client/src/components/Header/NavBar/NavBar.tsx
  client/src/components/ProductList/ProductItem/ProductItemImage.tsx
  client/src/components/Review/ReviewHeader/ReviewHeader.tsx
  client/src/pages/Account.tsx
  client/src/pages/Product.tsx
Labels: enhancement, feature, frontend

#117 [#114] ProductDetail Store 및 해당 상품 fetch API 요청
  client/src/api/product.ts
  client/src/stores/productDetailStore.ts
  client/src/types/product.ts
Labels: feature, frontend

#122 [#121] ProductDetailStore 내보낼때 인스턴스로 내보내기
  client/src/stores/productDetailStore.ts
Labels: bug, frontend

#123 [#120] 상품 디테일 UI API와 연동 및 오류 처리
  client/src/containers/ProductDetailContainer.tsx
  client/src/hooks/useCartsInProduct.ts
  client/src/hooks/useDetailProduct.ts
  client/src/models/product-option.ts
  client/src/models/product.ts
  client/src/stores/productDetailStore.ts
  client/src/types/product.ts
  client/src/utils/typeGuard.ts
  server/src/controllers/product-controller.ts
  server/src/validations/number-params.ts
Labels: feature, frontend

#124 [#119] 메인페이지 상품 목록 API 연결 & Error 페이지
  client/src/api/product.ts
  client/src/components/App/App.tsx
  client/src/components/MainProductSections/MainProductList.tsx
  client/src/components/MainProductSections/MainProductSections.tsx
  client/src/components/MainProductSections/hooks/useProductAdList.ts
  client/src/components/MainProductSections/hooks/useProductList.ts
  client/src/containers/MainProductSectionsContainer.tsx
  client/src/hooks/useMainAdProductList.ts
  client/src/hooks/useMainProductList.ts
  client/src/pages/Error.tsx
  client/src/pages/Home.tsx
  client/src/stores/productStore.ts
  client/src/types/product.ts
Labels: feature, frontend

#126 [#118] 프론트엔드 로그인 처리, 백엔드와 연동, user 전역 상태로 관리
  client/src/api/index.ts
  client/src/api/user.ts
  client/src/components/App/App.tsx
  client/src/components/Header/Header.tsx
  client/src/components/Header/NavBar/NavBar.tsx
  client/src/components/Login/OAuthButton.tsx
  client/src/components/Logout/Logout.tsx
  client/src/containers/LogoutContainer.tsx
  client/src/containers/NavBarContianer.tsx
  client/src/models/user.ts
  client/src/pages/Logout.tsx
  client/src/stores/userStore.ts
  client/src/types/user.ts
  server/src/controllers/auth-controller.ts
  server/src/routers/auth/index.ts
Labels: feature, frontend, backend

#129 [#125] 상품 상세 후기 리스트 API 연동
  client/src/components/ProductDetail/ProductDetail.tsx
  client/src/components/Review/Review.test.tsx
  client/src/components/Review/Review.tsx
  client/src/components/Review/ReviewList/ReviewList.tsx
  client/src/components/Review/ReviewList/ReviewListItem/ReviewDetail/ReviewDetail.tsx
  client/src/components/Review/ReviewList/ReviewListItem/ReviewListItem.tsx
  client/src/containers/ReviewContainer.tsx
  client/src/models/review.ts
  client/src/pages/Product.tsx
Labels: feature, frontend

#127 [#113] 배송지 관리 API
  server/src/controllers/delivery-address-controller.ts
  server/src/exceptions/delivery-address-notfound-exception.ts
  server/src/exceptions/not-my-delivery-address-exception.ts
  server/src/middlewares/error-middleware.ts
  server/src/repositories/delivery-address-repository.ts
  server/src/routers/api/delivery-address/index.ts
  server/src/routers/api/index.ts
  server/src/services/delivery-address-service.ts
  server/src/validations/delivery-address-create.ts
  server/src/validations/delivery-address-modify.ts
Labels: feature, backend

#109 [#66] 장바구니 페이지 UI 및 기능
  client/src/assets/icons/close.png
  client/src/assets/icons/next.png
  client/src/assets/icons/next_off.png
  client/src/assets/images/equal.png
  client/src/assets/images/plus.png
  client/src/components/App/App.tsx
  client/src/components/Cart/Cart.tsx
  client/src/components/Cart/CartButtons/CartButtons.tsx
  client/src/components/Cart/CartHeader/CartHeader.tsx
  client/src/components/Cart/CartModal/CartModal.tsx
  client/src/components/Cart/CartModal/CountOption/CountOption.tsx
  client/src/components/Cart/CartModal/OptionContainer/OptionContainer.tsx
  client/src/components/Cart/CartTable/CartItem/CartItem.tsx
  client/src/components/Cart/CartTable/CartTable.tsx
  client/src/components/Cart/CartTable/TableHeader/TableHeader.tsx
  client/src/components/Cart/PriceTotalWrapper/PriceTotalWrapper.tsx
  client/src/components/Cart/addProductToCartEX.tsx
  client/src/components/Cart/helper.ts
  client/src/containers/CartContainer.tsx
  client/src/models/cart-item.ts
  client/src/pages/Cart.tsx
  client/src/stores/cartStore.ts
  client/src/types/cart.ts
  client/src/utils/hasProperty.ts
  client/src/utils/moneyFormater.ts
Labels: feature, frontend

#130 [#128] 상품 상세에서 찜하기 기능 API 연동
  client/src/api/product.ts
  client/src/components/ProductDetail/ProductDetail.tsx
  client/src/components/ProductDetail/ProductInfoBox.test.tsx
  client/src/components/ProductDetail/ProductInfoBox.tsx
  client/src/containers/ProductDetailContainer.tsx
  client/src/stores/productDetailStore.ts
  server/src/controllers/wish-controller.ts
  server/src/repositories/wish-repository.ts
  server/src/routers/api/product/index.ts
  server/src/services/wish-service.ts
Labels: feature, frontend

#132 [#68] 최근 검색 드롭다운 UI
  client/src/components/Header/HeaderMain/CategoryMenu/CategoryLayer.tsx
  client/src/components/Header/HeaderMain/HeaderMain.tsx
  client/src/components/Header/HeaderMain/SearchBar/Dropdown.test.tsx
  client/src/components/Header/HeaderMain/SearchBar/Dropdown.tsx
  client/src/components/Header/HeaderMain/SearchBar/SearchBar.tsx
  client/src/components/Header/HeaderMain/SearchBar/SearchTermList/SearchTermItem.tsx
  client/src/components/Header/HeaderMain/SearchBar/SearchTermList/SearchTermList.tsx
  client/src/containers/ProductListContainer.tsx
  client/src/containers/SearchBarContainer.tsx
  client/src/models/searchTerm.ts
  client/src/stores/optionStore.ts
Labels: feature, frontend

#133 [#68] products api에 where like 추가
  server/src/repositories/product-repository.ts
  server/src/validations/product-find-query.ts
Labels: feature, backend

#134 [#131] 배송지 관리 API 연동
  client/src/api/deliveryAddress.ts
  client/src/api/index.ts
  client/src/components/DeliveryAddress/CreateDeliveryAddressForm.tsx
  client/src/components/DeliveryAddress/DeliveryAddressItem/DeliveryAddressItem.test.tsx
  client/src/components/DeliveryAddress/DeliveryAddressItem/DeliveryAddressItem.tsx
  client/src/components/DeliveryAddress/DeliveryAddressItem/ModifyDeliveryAddressForm.test.tsx
  client/src/components/DeliveryAddress/DeliveryAddressItem/ModifyDeliveryAddressForm.tsx
  client/src/components/DeliveryAddress/DeliveryAddressList.test.tsx
  client/src/components/DeliveryAddress/DeliveryAddressList.tsx
  client/src/containers/DeliveryAddressItemContainer.tsx
  client/src/containers/ManageDeliveryAddressContainer.tsx
  client/src/pages/Account.tsx
  client/src/stores/deliveryAddressStore.ts
  client/src/types/deliveryAddress.ts
Labels: feature, frontend

#142 [#139] 마이페이지 기본 레이아웃
  client/src/components/Account/AccountLanding/AccountLanding.tsx
  client/src/components/Account/AccountNavList/AccountNavList.tsx
  client/src/components/App/App.tsx
  client/src/pages/Account.tsx
Labels: feature, frontend

#135 [#65] 상품 리뷰 작성 기능
  client/src/api/index.ts
  client/src/api/review.ts
  client/src/components/ProductDetail/ProductCart/ProductCartItem.test.tsx
  client/src/components/ProductDetail/ProductDetail.tsx
  client/src/components/ProductDetail/ProductInfoBox.test.tsx
  client/src/components/ProductList/ProductItem.test.tsx
  client/src/components/Review/Review.test.tsx
  client/src/components/Review/ReviewHeader/ReviewHeader.tsx
  client/src/components/Review/ReviewPost/ReviewPost.test.tsx
  client/src/components/Review/ReviewPost/ReviewPost.tsx
  client/src/components/Review/ReviewPost/ReviewPostModal/ReviewPostForm/ReviewPostButtonGroup/ReviewPostButtonGroup.tsx
  client/src/components/Review/ReviewPost/ReviewPostModal/ReviewPostForm/ReviewPostForm.tsx
  client/src/components/Review/ReviewPost/ReviewPostModal/ReviewPostForm/ReviewPostImages/ReviewPostImages.tsx
  client/src/components/Review/ReviewPost/ReviewPostModal/ReviewPostForm/ReviewPostText/ReviewPostText.tsx
  client/src/components/Review/ReviewPost/ReviewPostModal/ReviewPostModal.tsx
  client/src/containers/ReviewContainer.tsx
  client/src/containers/ReviewPostContainer.tsx
  client/src/containers/ReviewPostFormContainer.tsx
  client/src/lib/request.ts
  client/src/models/product.test.tsx
  client/src/models/product.ts
  client/src/stores/reviewStore.ts
  client/src/stores/userStore.ts
  server/.env.sample
  server/package-lock.json
  server/package.json
  server/src/config/dotenv.ts
  server/src/controllers/review-controller.ts
  server/src/exceptions/product-notordered-exception.ts
  server/src/exceptions/review-notfound-exception.ts
  server/src/exceptions/review-notwrittenbyuser-exception.ts
  server/src/middlewares/error-middleware.ts
  server/src/middlewares/form-middleware.ts
  server/src/repositories/product-repository.ts
  server/src/repositories/user-repository.ts
  server/src/routers/api/index.ts
  server/src/routers/api/review/index.ts
  server/src/services/product-service.ts
  server/src/services/review-service.ts
  server/src/services/s3-service.ts
  server/src/types/express.d.ts
  server/src/validations/review-post.ts
Labels: feature, frontend, backend

#137 [#136] 주문 조회 및 생성 API
  server/package-lock.json
  server/package.json
  server/src/controllers/order-controller.ts
  server/src/exceptions/option-notfound-excepiton.ts
  server/src/repositories/order-repository.ts
  server/src/routers/api/index.ts
  server/src/routers/api/order/index.ts
  server/src/services/order-service.ts
  server/src/validations/order-create.ts
Labels: feature, backend

#212 [#153] OptionStore 동작 방식 개선
  client/src/api/product.ts
  client/src/components/Header/HeaderMain/CategoryMenu/CategoryLayer.test.tsx
  client/src/components/Header/HeaderMain/CategoryMenu/CategoryLayer.tsx
  client/src/components/PaymentFinish/ShippingInfo.tsx
  client/src/components/ProductList/ProductList.test.tsx
  client/src/components/ProductList/SortButtonList.test.tsx
  client/src/components/WishList/WishItem/WishItem.tsx
  client/src/containers/CategoryLayerContainer.tsx
  client/src/containers/ProductListContainer.tsx
  client/src/containers/SearchBarContainer.tsx
  client/src/hooks/useOption.ts
  client/src/lib/router.tsx
  client/src/stores/optionStore.ts
Labels: bug, enhancement, feature

#215 [#214] 마지막 검색어 입력 시 창이 닫히는 오류
  client/src/containers/SearchBarContainer.tsx
Labels: bug, frontend

#217 [#213] [#216] 토큰 사용 방식 통일 및 에러 처리 / 인증 필요한 컴포넌트 접근시 처리
  client/src/components/Authentication/Authentication.tsx
  client/src/components/Header/Badge/Badge.tsx
  client/src/components/Header/NavBar/NavBar.tsx
  client/src/containers/DeliveryAddressItemContainer.tsx
  client/src/containers/ManageDeliveryAddressContainer.tsx
  client/src/containers/NavBarContianer.tsx
  client/src/containers/OrderPaymentContainer.tsx
  client/src/containers/ReviewPostFormContainer.tsx
  client/src/hoc/withAuthentication.tsx
  client/src/hooks/useWish.ts
  client/src/lib/router.tsx
  client/src/pages/Account.tsx
  client/src/pages/Order.tsx
  client/src/stores/deliveryAddressStore.ts
  client/src/stores/orderStore.ts
  client/src/stores/productDetailStore.ts
  client/src/stores/productStore.ts
  client/src/stores/reviewStore.ts
  client/src/stores/userStore.ts
  client/src/stores/wishStore.ts
  server/src/controllers/auth-controller.ts
  server/src/routers/auth/index.ts
Labels: enhancement, refactor, frontend

#220 [#219] 상품 수량 관련 버그 해결
  client/src/components/Cart/CartModal/CountOption/CountOption.tsx
  client/src/components/Cart/CartModal/CountOption/ProductCounter.tsx
  client/src/containers/ProductDetailContainer.tsx
  client/src/models/cart-in-product.ts
  client/src/models/cart-item.ts
  client/src/utils/typeGuard.ts
Labels: bug, frontend

#225 [#224] 장바구니: 전체 상품 주문 버튼 버그 해결
  client/src/containers/CartContainer.tsx
Labels: bug, frontend

#227 [#226] 장바구니에 기존하는 상품 추가시 잘못된 상품의 수량이 올라가는 버그 해결
  client/src/stores/cartStore.ts
Labels: bug, frontend

#229 [#223] 주문서 작성에 배송지 선택 기능 추가
  client/src/components/OrderPayment/OrderForm/OrderForm.tsx
  client/src/components/OrderPayment/OrderPayment.tsx
  client/src/containers/OrderPaymentContainer.tsx
Labels: feature, frontend

#236 상품상세 이미지 중앙 정렬하기
  client/src/components/ProductDetail/ProductDetail.tsx
Labels: enhancement, frontend

#222 [#221] 마이페이지 주문 관리 탭 추가
  client/src/api/order.ts
  client/src/components/Account/AccountOrder/AccountOrder.tsx
  client/src/components/Account/AccountOrder/AccountOrderTable/AccountOrderTableHeader.tsx
  client/src/components/Account/AccountOrder/AccountOrderTable/AccountOrderTableItem.tsx
  client/src/components/Account/AccountOrder/AccountOrderTable/AccountOrderTableItemDetail.tsx
  client/src/components/App/App.tsx
  client/src/containers/AccountOrderContainer.tsx
  client/src/models/order.ts
  client/src/models/orderDetail.ts
  client/src/models/orderDetailProduct.ts
  client/src/pages/Account.tsx
  client/src/pages/OrderPayment.tsx
  client/src/stores/orderStore.ts
  client/src/types/order.ts
  client/src/utils/formatDate.ts
  server/src/repositories/order-repository.ts
  server/src/services/order-service.ts
Labels: feature, frontend

#230 [#228] Order 관련 자잘한 버그 해결
  client/src/components/PaymentFinish/PaymentFinish.tsx
  client/src/containers/OrderPaymentContainer.tsx
  client/src/stores/cartStore.ts
  client/src/stores/orderStore.ts
Labels: bug, frontend

#231 [#93] 찜리스트 api & 연동
  client/src/api/product.ts
  client/src/components/WishList/EmptyMessageBox/EmptyMessageBox.tsx
  client/src/components/WishList/WishItem/WishItem.tsx
  client/src/components/WishList/WishList.tsx
  client/src/components/WishList/mock.ts
  client/src/stores/wishStore.ts
  client/src/types/Wish.ts
  server/src/controllers/wish-controller.ts
  server/src/repositories/wish-repository.ts
  server/src/routers/api/product/index.ts
  server/src/services/wish-service.ts
Labels: feature, frontend, backend

#233 [#232] 상품 목록 Pagination 개선
  client/src/components/ProductList/ProductList.test.tsx
  client/src/components/ProductList/ProductList.tsx
  client/src/components/Review/ReviewPagination/ReviewPagination.tsx
Labels: enhancement, frontend

#238 [#237] 메인 AD 링크 걸어주기
  client/src/components/Carousel/Carousel.test.tsx
  client/src/components/Carousel/Carousel.tsx
  client/src/components/Carousel/CarouselController.test.tsx
  client/src/components/MainProductSections/MainAdList/MainAdListItem.tsx
  client/src/components/MainProductSections/mock/index.ts
  client/src/containers/CarouselContainer.tsx
Labels: enhancement, frontend

#240 [#239] production 환경 배포 스크립트
  .github/workflows/prod-server-cd.yml
Labels: feature

#254 [#246] 웹 접근성 향상
  client/src/components/Account/AccountOrder/AccountOrderTable/AccountOrderTableItemDetail.tsx
  client/src/components/Cart/Cart.tsx
  client/src/components/Cart/CartModal/CountOption/ProductCounter.tsx
  client/src/components/Cart/CartModal/OptionContainer/OptionContainer.tsx
  client/src/components/Cart/CartTable/CartItem/CartItem.tsx
  client/src/components/Footer/Footer.tsx
  client/src/components/Header/HeaderMain/HeaderMain.tsx
  client/src/components/Header/HeaderMain/SearchBar/SearchBar.tsx
  client/src/components/Header/NavBar/NavBar.tsx
  client/src/components/MainProductSections/MainAdList/MainAdListItem.tsx
  client/src/components/MainProductSections/MainProductList.tsx
  client/src/components/OrderPayment/OrderTable/OrderDetailProductItem.tsx
  client/src/components/ProductDetail/ProductCart/ProductCartItem.tsx
  client/src/components/ProductDetail/ProductCart/ProductCounter.tsx
  client/src/components/ProductDetail/ProductImage/MagnifierImage.tsx
  client/src/components/ProductDetail/ProductImage/ProductDetailImages.tsx
  client/src/components/ProductDetail/ProductInfoBox.tsx
  client/src/components/ProductList/ProductItem/ProductItem.tsx
  client/src/components/ProductList/ProductItem/ProductItemImage.tsx
  client/src/components/Review/ReviewList/ReviewListItem/ReviewDetail/ReviewDetailImage/ReviewDetailImage.tsx
  client/src/components/Review/ReviewPost/ReviewPostModal/ReviewPostForm/ReviewPostImages/ReviewPostImages.tsx
  client/src/components/WishList/WishItem/WishItem.tsx
  client/src/index.html
  client/src/lib/router.tsx
Labels: enhancement, frontend

#261 [#257] 이미지 사이즈 명시
  client/src/components/Account/AccountOrder/AccountOrderTable/AccountOrderTableItemDetail.tsx
  client/src/components/Cart/CartModal/OptionContainer/OptionContainer.tsx
  client/src/components/Footer/Footer.tsx
  client/src/components/Header/HeaderMain/HeaderMain.tsx
  client/src/components/MainProductSections/MainAdList/MainAdListItem.tsx
  client/src/components/ProductDetail/ProductImage/MagnifierImage.tsx
  client/src/components/ProductDetail/ProductImage/ProductDetailImages.tsx
  client/src/components/ProductList/ProductItem/ProductItemImage.tsx
  client/src/components/Review/ReviewList/ReviewListItem/ReviewDetail/ReviewDetailImage/ReviewDetailImage.tsx
  client/src/components/Review/ReviewPost/ReviewPostModal/ReviewPostForm/ReviewPostImages/ReviewPostImages.tsx
Labels: enhancement, frontend

#263 Revert [#246] 웹 접근성 향상
  client/src/components/Account/AccountOrder/AccountOrderTable/AccountOrderTableItemDetail.tsx
  client/src/components/Cart/Cart.tsx
  client/src/components/Cart/CartModal/CountOption/ProductCounter.tsx
  client/src/components/Cart/CartModal/OptionContainer/OptionContainer.tsx
  client/src/components/Cart/CartTable/CartItem/CartItem.tsx
  client/src/components/Footer/Footer.tsx
  client/src/components/Header/HeaderMain/HeaderMain.tsx
  client/src/components/Header/HeaderMain/SearchBar/SearchBar.tsx
  client/src/components/Header/NavBar/NavBar.tsx
  client/src/components/MainProductSections/MainAdList/MainAdListItem.tsx
  client/src/components/MainProductSections/MainProductList.tsx
  client/src/components/OrderPayment/OrderTable/OrderDetailProductItem.tsx
  client/src/components/ProductDetail/ProductCart/ProductCartItem.tsx
  client/src/components/ProductDetail/ProductCart/ProductCounter.tsx
  client/src/components/ProductDetail/ProductImage/MagnifierImage.tsx
  client/src/components/ProductDetail/ProductImage/ProductDetailImages.tsx
  client/src/components/ProductDetail/ProductInfoBox.tsx
  client/src/components/ProductList/ProductItem/ProductItem.tsx
  client/src/components/ProductList/ProductItem/ProductItemImage.tsx
  client/src/components/Review/ReviewList/ReviewListItem/ReviewDetail/ReviewDetailImage/ReviewDetailImage.tsx
  client/src/components/Review/ReviewPost/ReviewPostModal/ReviewPostForm/ReviewPostImages/ReviewPostImages.tsx
  client/src/components/WishList/WishItem/WishItem.tsx
  client/src/index.html
  client/src/lib/router.tsx
Labels: frontend

#264 [#246] 웹 접근성 향상
  client/src/components/Account/AccountOrder/AccountOrderTable/AccountOrderTableItemDetail.tsx
  client/src/components/Cart/Cart.tsx
  client/src/components/Cart/CartModal/CountOption/ProductCounter.tsx
  client/src/components/Cart/CartModal/OptionContainer/OptionContainer.tsx
  client/src/components/Cart/CartTable/CartItem/CartItem.tsx
  client/src/components/Footer/Footer.tsx
  client/src/components/Header/HeaderMain/HeaderMain.tsx
  client/src/components/Header/HeaderMain/SearchBar/SearchBar.tsx
  client/src/components/Header/NavBar/NavBar.tsx
  client/src/components/MainProductSections/MainAdList/MainAdListItem.tsx
  client/src/components/MainProductSections/MainProductList.tsx
  client/src/components/OrderPayment/OrderTable/OrderDetailProductItem.tsx
  client/src/components/ProductDetail/ProductCart/ProductCartItem.tsx
  client/src/components/ProductDetail/ProductCart/ProductCounter.tsx
  client/src/components/ProductDetail/ProductImage/MagnifierImage.tsx
  client/src/components/ProductDetail/ProductImage/ProductDetailImages.tsx
  client/src/components/ProductDetail/ProductInfoBox.tsx
  client/src/components/ProductList/ProductItem/ProductItem.tsx
  client/src/components/ProductList/ProductItem/ProductItemImage.tsx
  client/src/components/Review/ReviewList/ReviewListItem/ReviewDetail/ReviewDetailImage/ReviewDetailImage.tsx
  client/src/components/Review/ReviewPost/ReviewPostModal/ReviewPostForm/ReviewPostImages/ReviewPostImages.tsx
  client/src/components/WishList/WishItem/WishItem.tsx
  client/src/index.html
  client/src/lib/router.tsx
Labels: enhancement, frontend

#245 [#242] init sql에 상품 옵션 추가
  server/init.sql
Labels: enhancement, backend

#247 [#244] 메인 AD 링크 ID 수정
  client/src/components/MainProductSections/mock/index.ts
  client/src/containers/CarouselContainer.tsx
Labels: enhancement, frontend

#249 [#248] 상품 목록 페이지 번호
  client/src/containers/ProductListContainer.tsx
  client/src/pages/Products.tsx
Labels: bug, enhancement, frontend

#252 [#251] 내 상품후기 제목 추가
  client/src/components/Account/AccountReview/AccountReview.tsx
Labels: enhancement, frontend

#255 [#253] useHistory 사용 / 불필요한 window.history.replaceState() 제거
  client/src/hoc/withAuthentication.tsx
  client/src/pages/Account.tsx
  client/src/pages/OrderPayment.tsx
  client/src/stores/userStore.ts
Labels: enhancement, refactor, frontend

#256 [#250] 토스트 색상 정리
  client/src/containers/CartContainer.tsx
  client/src/containers/DeliveryAddressItemContainer.tsx
  client/src/containers/ManageDeliveryAddressContainer.tsx
  client/src/containers/OrderPaymentContainer.tsx
  client/src/containers/ProductDetailContainer.tsx
  client/src/containers/ReviewPostFormContainer.tsx
  client/src/hooks/useWish.ts
Labels: enhancement, frontend

#258 [#243] 주문 페이지 옵션 없는 경우 X 삭제, 주문서 작성 select 스타일
  client/src/components/Account/AccountOrder/AccountOrderTable/AccountOrderTableItemDetail.tsx
  client/src/components/OrderPayment/OrderForm/OrderForm.tsx
  client/src/components/OrderPayment/OrderTable/OrderDetailProductItem.tsx
Labels: feature, frontend

#260 [#259] 페이스북 로그인 주석 제거, 테스트 코드 수정
  client/src/components/Login/Login.test.tsx
  client/src/components/Login/Login.tsx
  client/src/containers/LoginContainer.tsx
  client/src/stores/userStore.ts
Labels: frontend

#266 [#265] 찜하기 버튼 UX 통일
  client/src/components/WishList/WishItem/WishItem.tsx
Labels: enhancement, frontend

#268 [#267] 배송지 관리에서 삭제 시 confirm 모달
  client/src/components/ConfirmModal/ConfirmModal.tsx
  client/src/containers/DeliveryAddressItemContainer.tsx
Labels: feature, frontend

#269 [#262] 코드 스플리팅 및 웹팩 설정 변경
  client/src/components/App/App.tsx
  client/src/components/Loading/Loading.tsx
  client/src/components/ProductList/ProductItem/ProductItemDescription.tsx
  client/webpack.common.js
  client/webpack.prod.js
Labels: enhancement, frontend

#273 [#272] 사용하지 않는 폰트 제거
  client/src/components/Cart/Cart.tsx
  client/src/index.html
Labels: enhancement, frontend

#271 거의 모든 이미지 레이지 로딩 컴포넌트 적용
  client/src/components/Account/AccountOrder/AccountOrderTable/AccountOrderTableItemDetail.tsx
  client/src/components/Cart/CartModal/OptionContainer/OptionContainer.tsx
  client/src/components/Cart/CartTable/CartItem/CartItem.tsx
  client/src/components/LazyImage/LazyImage.tsx
  client/src/components/MainProductSections/MainAdList/MainAdListItem.tsx
  client/src/components/OrderPayment/OrderTable/OrderDetailProductItem.tsx
  client/src/components/ProductDetail/ProductImage/MagnifierImage.tsx
  client/src/components/ProductList/ProductItem/ProductItemImage.tsx
  client/src/components/Review/ReviewList/ReviewListItem/ReviewDetail/ReviewDetailImage/ReviewDetailImage.tsx
  client/src/components/WishList/WishItem/WishItem.tsx
Labels: enhancement, feature

#275 [#274] 콘솔로그 제거, 시연용 아이디 uuid 적용
  client/src/components/LazyImage/LazyImage.tsx
  server/src/controllers/auth-controller.ts
Labels: bug, feature, frontend, backend

#276 v1.0.1
  client/src/components/Account/AccountOrder/AccountOrderTable/AccountOrderTableItemDetail.tsx
  client/src/components/Account/AccountReview/AccountReview.tsx
  client/src/components/App/App.tsx
  client/src/components/Cart/Cart.tsx
  client/src/components/Cart/CartModal/OptionContainer/OptionContainer.tsx
  client/src/components/Cart/CartTable/CartItem/CartItem.tsx
  client/src/components/ConfirmModal/ConfirmModal.tsx
  client/src/components/Footer/Footer.tsx
  client/src/components/Header/HeaderMain/HeaderMain.tsx
  client/src/components/LazyImage/LazyImage.tsx
  client/src/components/Loading/Loading.tsx
  client/src/components/Login/Login.test.tsx
  client/src/components/Login/Login.tsx
  client/src/components/MainProductSections/MainAdList/MainAdListItem.tsx
  client/src/components/MainProductSections/mock/index.ts
  client/src/components/OrderPayment/OrderForm/OrderForm.tsx
  client/src/components/OrderPayment/OrderTable/OrderDetailProductItem.tsx
  client/src/components/ProductDetail/ProductImage/MagnifierImage.tsx
  client/src/components/ProductDetail/ProductImage/ProductDetailImages.tsx
  client/src/components/ProductList/ProductItem/ProductItemDescription.tsx
  client/src/components/ProductList/ProductItem/ProductItemImage.tsx
  client/src/components/Review/ReviewList/ReviewListItem/ReviewDetail/ReviewDetailImage/ReviewDetailImage.tsx
  client/src/components/Review/ReviewPost/ReviewPostModal/ReviewPostForm/ReviewPostImages/ReviewPostImages.tsx
  client/src/components/WishList/WishItem/WishItem.tsx
  client/src/containers/CarouselContainer.tsx
  client/src/containers/CartContainer.tsx
  client/src/containers/DeliveryAddressItemContainer.tsx
  client/src/containers/LoginContainer.tsx
  client/src/containers/ManageDeliveryAddressContainer.tsx
  client/src/containers/OrderPaymentContainer.tsx
  client/src/containers/ProductDetailContainer.tsx
  client/src/containers/ProductListContainer.tsx
  client/src/containers/ReviewPostFormContainer.tsx
  client/src/hoc/withAuthentication.tsx
  client/src/hooks/useWish.ts
  client/src/index.html
  client/src/pages/Account.tsx
  client/src/pages/OrderPayment.tsx
  client/src/pages/Products.tsx
  client/src/stores/userStore.ts
  client/webpack.common.js
  client/webpack.prod.js
  server/init.sql
  server/src/controllers/auth-controller.ts
Labels: release

#278 [#277] 웹 접근성 향상 적용
  client/src/components/Cart/Cart.tsx
  client/src/components/Cart/CartModal/CountOption/ProductCounter.tsx
  client/src/components/Footer/Footer.tsx
  client/src/components/Header/HeaderMain/HeaderMain.tsx
  client/src/components/Header/HeaderMain/SearchBar/SearchBar.tsx
  client/src/components/Header/NavBar/NavBar.tsx
  client/src/components/MainProductSections/MainProductList.tsx
  client/src/components/ProductDetail/ProductCart/ProductCartItem.tsx
  client/src/components/ProductDetail/ProductCart/ProductCounter.tsx
  client/src/components/ProductDetail/ProductInfoBox.tsx
  client/src/components/ProductList/ProductItem/ProductItem.tsx
  client/src/components/Review/ReviewPost/ReviewPostModal/ReviewPostForm/ReviewPostImages/ReviewPostImages.tsx
  client/src/index.html
  client/src/lib/router.tsx
Labels: enhancement, frontend

#280 [#279] 페이스북 로그인 주석처리
  client/src/components/Login/Login.test.tsx
  client/src/components/Login/Login.tsx
  client/src/containers/LoginContainer.tsx
Labels: feature, frontend

#281 v.1.0.2
  client/src/components/Cart/Cart.tsx
  client/src/components/Cart/CartModal/CountOption/ProductCounter.tsx
  client/src/components/Footer/Footer.tsx
  client/src/components/Header/HeaderMain/HeaderMain.tsx
  client/src/components/Header/HeaderMain/SearchBar/SearchBar.tsx
  client/src/components/Header/NavBar/NavBar.tsx
  client/src/components/Login/Login.test.tsx
  client/src/components/Login/Login.tsx
  client/src/components/MainProductSections/MainProductList.tsx
  client/src/components/ProductDetail/ProductCart/ProductCartItem.tsx
  client/src/components/ProductDetail/ProductCart/ProductCounter.tsx
  client/src/components/ProductDetail/ProductInfoBox.tsx
  client/src/components/ProductList/ProductItem/ProductItem.tsx
  client/src/components/Review/ReviewPost/ReviewPostModal/ReviewPostForm/ReviewPostImages/ReviewPostImages.tsx
  client/src/containers/LoginContainer.tsx
  client/src/index.html
  client/src/lib/router.tsx
Labels: release

#283 [#282] 리뷰 디테일 이미지 중복 제거
  client/src/components/Review/ReviewList/ReviewListItem/ReviewDetail/ReviewDetailImage/ReviewDetailImage.tsx
Labels: bug, frontend

#284 v1.0.3
  client/src/components/Review/ReviewList/ReviewListItem/ReviewDetail/ReviewDetailImage/ReviewDetailImage.tsx
Labels: release

#286 [#285] README 정리
  README.md
Labels: documentation

#287 Docs README
  README.md
Labels: documentation

#289 [#288] React lazy Fallback 컴포넌트
  client/src/components/App/App.tsx
  client/src/components/Loading/Loading.tsx
Labels: bug, enhancement, frontend

#290 v1.0.4
  client/src/components/App/App.tsx
  client/src/components/Loading/Loading.tsx
Labels: release
